### PR TITLE
Update r

### PR DESCRIPTION
**Pull request by jpainter**

### CODE REVIEW

**Comment by skomanduri** [comment]
Hi @jpainter, thanks for the PR!  We'll get back to you with a response soon.

Quick note: Each line in the Dockerfile is a separate build step, so the best practice is to combine all the packages you want to install into one line like so: https://github.com/civisanalytics/civis-services-shiny/blob/d9b545c8cfe3bffbe5da1e59da24b75d579f009d/Dockerfile

cc @patr1ckm

**Comment by patr1ckm** [comment]
Thanks for the PR @jpainter.

However, we won't be able to accept the PR for merging into master. We'd recommend that you build this image yourself and host it on dockerhub. You can then point your service to use that image.

Alternatively, tagging a release pointed at a branch on this repo will build a `civis-services-shiny/dev-[branchname]` image on dockerhub that you can use for your service as well. 

We'll look at adding some of the geospatial packages you have listed here in the base `datascience-r` image because it's a request we hear frequently.

Let us know if you have any questions!

**Comment by jpainter** [comment]
Hi Patrick, Thanks for the message.  I just rebuilt an image on docker hub and will go that route.

Thanks for considering adding the Geometry Engine (GEOS) to the image, a requirement for several R geospatial packages. In addition, it would be great to include more packages than just Shiny.  The issue is that I develop shiny apps on my machine, and then have to configure a new docker image just to run that app, because the master branch only has shiny installed.

Shiny is never the only package needed.  Of course each shiny app will use different sets of package.  It is possible, however, to have many of the most common packages available, such that it is not necessary to build a new image.  A new app does not need to load all the installed packages, but having them installed is a huge convenience.  Especially for those packages that have multiple dependencies.  For example, many shiny apps would call the tidyverse package<https://cran.r-project.org/web/packages/tidyverse/index.html> , which needs to install at least 26 packages, each with their own set of dependencies.

Thanks for considering these changes.

Best, John

John Painter, DVM, MS
Surveillance, Monitoring, and Evaluation Team Lead
CDC-President’s Malaria Initiative,
Malaria Branch,
Division of Parasitic Diseases and Malaria,
US Centers for Disease Control and Prevention,
Atlanta, GA
Mailstop A-06

**Comment by patr1ckm** [comment]
Thanks @jpainter! I've scraped some data on package installs from across Civis users, and will use that to guide inclusion of packages in the base image by default. We may be able to accommodate additional packages (subject to size constraints) if you reach out to support, or filing an issue at https://github.com/civisanalytics/datascience-r/issues.

**Pull request closed without merging**
