### PR TITLE
[1.6.0] use datascience-r 3.3.0

### PR DESCRIPTION
**Pull request by mattle24**

### CODE REVIEW

**Comment by patr1ckm** [comment]
Can you also test this on a simple shiny app? I verified that `dev-3.3.0 (f1194b37)` is building for use

**Comment by mattle24** [comment]
I can try, I have not run a shiny app since summer 2018 so might not be able to.

**Comment by patr1ckm** [comment]
https://platform.civisanalytics.com/spa/#/services/477 worked for me here, update the change log and we should be g2g

**Comment by mattle24** [comment]
@patr1ckm CI finally passed it!

**Pull request merged**
